services:
  web:
    image: docker.0rays.club/cbctf/test-web:20250609
    ports:
      - "5000:5000"
    environment:
      - FLAG_0=uuid{}
      - FLAG_1=dynamic{this_is_a_dynamic_flag}
    volumes:
      - FLAG_3:/flag

  db:
    image: docker.0rays.club/library/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testdb

volumes:
  FLAG_3:
    labels:
      - value=static{this_is_a_static_flag}
