apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cbctf.fullname" . }}
  labels:
    {{- include "cbctf.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    resourceNames: [{{ .Release.Namespace | quote }}]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: ["kubeovn.io"]
    resources: ["subnets"]
    verbs: ["create", "get", "deletecollection"]
  - apiGroups: ["kubeovn.io"]
    resources: ["vpcs"]
    verbs: ["create", "deletecollection"]
  - apiGroups: ["kubeovn.io"]
    resources: ["ips"]
    verbs: ["deletecollection"]
