apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cbctf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cbctf.labels" . | nindent 4 }}
data:
  config.yaml: |
    host: {{ .Values.cbctf.host | quote }}
    path: /app/data

    asynq:
      log:
        level: {{ .Values.cbctf.asynq.log.level | quote }}
      queues:
        victim: {{ .Values.cbctf.asynq.queues.victim }}
        traffic: {{ .Values.cbctf.asynq.queues.traffic }}
        generator: {{ .Values.cbctf.asynq.queues.generator }}
        attachment: {{ .Values.cbctf.asynq.queues.attachment }}
        email: {{ .Values.cbctf.asynq.queues.email }}
        webhook: {{ .Values.cbctf.asynq.queues.webhook }}
        image: {{ .Values.cbctf.asynq.queues.image }}

    gin:
      mode: {{ .Values.cbctf.gin.mode | quote }}
      host: {{ .Values.cbctf.gin.host | quote }}
      port: {{ .Values.cbctf.gin.port }}
      upload:
        picture: {{ .Values.cbctf.gin.upload.picture }}
        challenge: {{ .Values.cbctf.gin.upload.challenge }}
        writeup: {{ .Values.cbctf.gin.upload.writeup }}
      proxies: {{ toYaml .Values.cbctf.gin.proxies | nindent 8 }}
      ratelimit:
        global: {{ .Values.cbctf.gin.ratelimit.global }}
        whitelist: {{ toYaml .Values.cbctf.gin.ratelimit.whitelist | nindent 10 }}
      origins: {{ toYaml .Values.cbctf.gin.origins | nindent 8 }}
      log:
        whitelist: {{ toYaml .Values.cbctf.gin.log.whitelist | nindent 10 }}
      jwt:
        secret: {{ .Values.cbctf.gin.jwt.secret | quote }}
      metrics:
        whitelist: {{ toYaml .Values.cbctf.gin.metrics.whitelist | nindent 10 }}
      pprof:
        whitelist: {{ toYaml .Values.cbctf.gin.pprof.whitelist | nindent 10 }}

    gorm:
      postgres:
        host: {{ include "cbctf.postgres.host" . | quote }}
        port: {{ .Values.postgres.service.port }}
        user: {{ .Values.postgres.auth.username | quote }}
        pwd: {{ .Values.postgres.auth.password | quote }}
        db: {{ .Values.postgres.auth.database | quote }}
        sslmode: {{ .Values.cbctf.gorm.postgres.sslmode }}
        mxopen: {{ .Values.cbctf.gorm.postgres.mxopen }}
        mxidle: {{ .Values.cbctf.gorm.postgres.mxidle }}
      log:
        level: {{ .Values.cbctf.gorm.log.level | quote }}

    redis:
      host: {{ include "cbctf.redis.host" . | quote }}
      port: {{ .Values.redis.service.port }}
      pwd: {{ .Values.redis.auth.password | quote }}

    k8s:
      namespace: {{ .Release.Namespace | quote }}
      shared_volume_claim: {{ default (printf "%s-shared-volume" .Release.Namespace) .Values.persistence.existingClaim | quote }}
      capture: {{ .Values.cbctf.k8s.capture | quote }}
      capture_enabled: {{ .Values.cbctf.k8s.captureEnabled }}
      priority_class_name: {{ .Values.cbctf.k8s.priorityClassName | quote }}
      worker_image: {{ .Values.cbctf.k8s.workerImage | quote }}
      generator_pool_size: {{ .Values.cbctf.k8s.generatorPoolSize }}
      frp:
        on: {{ .Values.cbctf.k8s.frp.on }}
        frpc: {{ .Values.cbctf.k8s.frp.frpc | quote }}
        nginx: {{ .Values.cbctf.k8s.frp.nginx | quote }}
        frps: {{ toYaml .Values.cbctf.k8s.frp.frps | nindent 10 }}

    cheat:
      ip:
        whitelist: {{ toYaml .Values.cbctf.cheat.ip.whitelist | nindent 10 }}

    webhook:
      whitelist: {{ toYaml .Values.cbctf.webhook.whitelist | nindent 8 }}

    registration:
      enabled: {{ .Values.cbctf.registration.enabled }}
      default_group: {{ .Values.cbctf.registration.default_group }}
