{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cbctf.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cbctf.postgres.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "cbctf.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
