{{- if .Values.redis.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbctf.redis.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cbctf.redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}
{{- end }}
