apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cbctf.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cbctf.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.cbctf.gin.jwt.secret | quote }}
