log:
    # DEBUG INFO WARNING ERROR
    level: "info"
    save: true
gin:
    mode: "release"
    host: "127.0.0.1"
    port: 8000
    proxies:
        - "10.0.0.1"
    upload:
        max: 8
    rate:
        window: 60
        max: 100
gorm:
    mysql:
        host: "127.0.0.1"
        port: 3306
        user: "cbctf"
        pwd: "password"
        db: "cbctf"
        mxopen: 100
        mxidle: 10
    log:
        # INFO WARNING ERROR SILENT
        level: "silent"
redis:
    host: "127.0.0.1"
    port: 6379
    pwd: "password"
    # millisecond
    timeout: 10
k8s:
    config:
        # admin will be ignored if user is set
        admin: "./admin.conf"
        user: "./user.conf"
    master: "192.168.0.1"
    # also as prefix of resources
    namespace: "cbctf"
    tcpdump: "nicolaka/netshoot:latest"
    frpc:
        on: false
        image: "docker.0rays.club/test/frpc:0.61.2"
        frps:
            -   host: "example.com"
                port: "7000"
                token: "token"
    # nodes of k8s cluster, used for external service
    nodes:
        - "192.168.0.1"
email:
    senders:
        -   addr: "noreply@example.com"
            pwd: "password"
            host: "smtp.example.com"
            port: 25
frontend: "http://127.0.0.1:3000"
backend: "http://127.0.0.1:8000"
path: "./uploads"
