serverAddr = "127.0.0.1"
serverPort = 7000
auth.token = "test_token"

[[proxies]]
name = "test"
type = "tcp"
localIP = "127.0.0.1"
localPort = 8000
remotePort = 30000
transport.proxyProtocolVersion = "v2"
