log:
  # DEBUG INFO WARNING ERROR
  level: info
  save: true
gin:
  mode: release
  host: 127.0.0.1
  port: 8000
gorm:
  file: data.db
  log:
    # INFO WARNING ERROR SILENT
    level: silent
upload:
  path: ./uploads
  max: 8
