/**
 * Builds update payload from nested config structure to flat structure expected by backend
 * @param {Object} config - Nested configuration object
 * @returns {Object} - Flat configuration payload
 */
export function buildPayload(config) {
  return {
    asyncq_concurrency: config.asyncq.concurrency,
    asyncq_log_level: config.asyncq.log.level,
    asyncq_victim_concurrency: config.asyncq.queues.victim,
    asyncq_generator_concurrency: config.asyncq.queues.generator,
    asyncq_attachment_concurrency: config.asyncq.queues.attachment,
    asyncq_email_concurrency: config.asyncq.queues.email,
    asyncq_webhook_concurrency: config.asyncq.queues.webhook,
    asyncq_image_concurrency: config.asyncq.queues.image,
    cheat_ip_whitelist: config.cheat.ip_whitelist,
    gin_metrics_whitelist: config.gin.metrics.whitelist,
    geocity_db: config.geocity_db,
    gin_cors: config.gin.cors,
    gin_host: config.gin.host,
    gin_jwt_secret: config.gin.jwt.secret || undefined,
    gin_log_whitelist: config.gin.log.whitelist,
    gin_mode: config.gin.mode,
    gin_port: config.gin.port,
    gin_proxies: config.gin.proxies,
    gin_ratelimit_global: config.gin.ratelimit.global,
    gin_ratelimit_whitelist: config.gin.ratelimit.whitelist,
    gin_upload_max: config.gin.upload.max,
    gorm_log_level: config.gorm.log.level,
    gorm_postgres_db: config.gorm.postgres.db,
    gorm_postgres_host: config.gorm.postgres.host,
    gorm_postgres_mxidle: config.gorm.postgres.mxidle,
    gorm_postgres_mxopen: config.gorm.postgres.mxopen,
    gorm_postgres_port: config.gorm.postgres.port,
    gorm_postgres_pwd: config.gorm.postgres.pwd || undefined,
    gorm_postgres_sslmode: config.gorm.postgres.sslmode,
    gorm_postgres_user: config.gorm.postgres.user,
    host: config.host,
    k8s_config: config.k8s.config,
    k8s_frp_frpc: config.k8s.frp.frpc,
    k8s_frp_frps: config.k8s.frp.frps,
    k8s_frp_nginx: config.k8s.frp.nginx,
    k8s_frp_on: config.k8s.frp.on,
    k8s_external_networks_enabled: config.k8s.external_networks?.enabled,
    k8s_external_networks_interfaces: config.k8s.external_networks?.interfaces || [],
    k8s_namespace: config.k8s.namespace,
    k8s_tcpdump: config.k8s.tcpdump,
    path: config.path,
    redis_host: config.redis.host,
    redis_port: config.redis.port,
    redis_pwd: config.redis.pwd || undefined,
    webhook_whitelist: config.webhook.whitelist,
    registration_enabled: config.registration.enabled,
    registration_default_group: config.registration.default_group,
  };
}
