/**
 * Builds update payload from nested config structure to flat structure expected by backend
 * @param {Object} config - Nested configuration object
 * @returns {Object} - Flat configuration payload
 */
export function buildPayload(config) {
  return {
    asyncq_concurrency: config.asyncq.concurrency,
    asyncq_log_level: config.asyncq.log.level,
    cheat_ip_whitelist: config.cheat.ip_whitelist,
    gin_metrics_whitelist: config.gin.metrics.whitelist,
    geocity_db: config.geocity_db,
    gin_cors: config.gin.cors,
    gin_host: config.gin.host,
    gin_jwt_secret: config.gin.jwt.secret || undefined,
    gin_jwt_static: config.gin.jwt.static,
    gin_log_whitelist: config.gin.log.whitelist,
    gin_mode: config.gin.mode,
    gin_port: config.gin.port,
    gin_proxies: config.gin.proxies,
    gin_ratelimit_global: config.gin.ratelimit.global,
    gin_ratelimit_whitelist: config.gin.ratelimit.whitelist,
    gin_upload_max: config.gin.upload.max,
    gorm_log_level: config.gorm.log.level,
    gorm_mysql_db: config.gorm.mysql.db,
    gorm_mysql_host: config.gorm.mysql.host,
    gorm_mysql_mxidle: config.gorm.mysql.mxidle,
    gorm_mysql_mxopen: config.gorm.mysql.mxopen,
    gorm_mysql_port: config.gorm.mysql.port,
    gorm_mysql_pwd: config.gorm.mysql.pwd || undefined,
    gorm_mysql_user: config.gorm.mysql.user,
    host: config.host,
    k8s_config: config.k8s.config,
    k8s_frp_frpc: config.k8s.frp.frpc,
    k8s_frp_frps: config.k8s.frp.frps,
    k8s_frp_nginx: config.k8s.frp.nginx,
    k8s_frp_on: config.k8s.frp.on,
    k8s_namespace: config.k8s.namespace,
    k8s_tcpdump: config.k8s.tcpdump,
    log_level: config.log.level,
    log_save: config.log.save,
    path: config.path,
    redis_host: config.redis.host,
    redis_port: config.redis.port,
    redis_pwd: config.redis.pwd || undefined,
    webhook_whitelist: config.webhook.whitelist,
    registration_enabled: config.registration.enabled,
    registration_default_group: config.registration.default_group,
  };
}
