services:
  web1:
    ports:
      - "5000:5000"
    environment:
      FLAG_1: uuid{}
    image: docker.0rays.club/cbctf/test-web:20250717
    networks:
      network1:
        ipv4_address: 192.168.0.2
      network2:
        ipv4_address: 192.168.1.2
    volumes:
      - FLAG_2:/flag
  web2:
    environment:
      FLAG_3: uuid{}
    image: docker.0rays.club/cbctf/test-web:20250717
    networks:
      network2:
        ipv4_address: 192.168.1.3
      network3:
        ipv4_address: 192.168.2.3
    volumes:
      - FLAG_4:/flag
  web3:
    environment:
      FLAG_5: uuid{}
    image: docker.0rays.club/cbctf/test-web:20250717
    networks:
      network3:
        ipv4_address: 192.168.2.4
    volumes:
      - FLAG_6:/flag
networks:
  network1:
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
    external: true
  network2:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  network3:
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
volumes:
  FLAG_2:
    labels:
      value: dynamic{this_is_a_dynamic_flag}
  FLAG_4:
    labels:
      value: dynamic{this_is_a_dynamic_flag}
  FLAG_6:
    labels:
      value: dynamic{this_is_a_dynamic_flag}
