services:
  web1:
    container_name: web1
    image: docker.0rays.club/cbctf/test-web:20250717
    cpus: 0.5
    mem_limit: 256m
    working_dir: /app
    command: ["python", "app.py"]
    ports:
      - "5000:5000"
    environment:
      APP_ENV: production
      FLAG_1: uuid{}
      FLAG_2: dynamic{this_is_a_dynamic_flag}
    x-volumes:
      - path: /flag
        content: dynamic{this_is_a_file_flag}
    x-kubevirt: true
    x-boot:
      bootloader: efi
      secure_boot: false
    x-cloudinit:
      user_data: |
        #cloud-config
        users:
          - name: root
    networks:
      network1:
        ipv4_address: 192.168.0.2
        mac_address: "00:00:00:00:01:01"
      network2:
        ipv4_address: 192.168.1.2
        mac_address: "00:00:00:00:01:02"

  web2:
    container_name: web2
    image: docker.0rays.club/cbctf/test-web:20250717
    cpus: 0.5
    mem_limit: 256m
    working_dir: /app
    command: ["python", "app.py"]
    environment:
      APP_ENV: production
      FLAG_3: uuid{}
    x-volumes:
      - path: /flag
        content: dynamic{this_is_a_file_flag}
    x-kubevirt: true
    x-boot:
      bootloader: efi
      secure_boot: false
    x-cloudinit:
      user_data: |
        #cloud-config
        users:
          - name: root
    networks:
      network2:
        ipv4_address: 192.168.1.3
        mac_address: "00:00:00:00:02:01"
      network3:
        ipv4_address: 192.168.2.3
        mac_address: "00:00:00:00:02:02"

  web3:
    container_name: web3
    image: docker.0rays.club/cbctf/test-web:20250717
    cpus: 0.5
    mem_limit: 256m
    working_dir: /app
    command: ["python", "app.py"]
    environment:
      APP_ENV: production
      FLAG_5: uuid{}
      FLAG_6: static{this_is_a_static_flag}
    x-volumes:
      - path: /flag
        content: dynamic{this_is_a_file_flag}
    x-kubevirt: false
    x-boot:
      bootloader: bios
    x-cloudinit:
      user_data: |
        #cloud-config
        users:
          - name: root
    networks:
      network3:
        ipv4_address: 192.168.2.4
        mac_address: "00:00:00:00:03:01"

networks:
  network1:
    external: true
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
  network2:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
  network3:
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1
